development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  host: <%= ENV['PRODUCTION_REDIS_HOST'] %>
  port: <%= ENV['PRODUCTION_REDIS_PORT'] %>
  password: <%= ENV['SECRET_KEY_BASE'] %>
  # url: redis://localhost:6379/1
  channel_prefix: qsmart-api_production
